# Generated by Django 5.2.8 on 2025-11-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('teacher', models.CharField(blank=True, max_length=200, verbose_name='Преподаватель')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.studygroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Расписание',
                'ordering': ['start_time'],
            },
        ),
    ]
