# Generated by Django 5.2.8 on 2025-11-15 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='week_type',
            field=models.CharField(choices=[('EVEN', 'Четная'), ('ODD', 'Нечетная'), ('BOTH', 'Еженедельно')], default='BOTH', max_length=4, verbose_name='Тип недели'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='headman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_of_group', to=settings.AUTH_USER_MODEL, verbose_name='Староста'),
        ),
    ]
